### ISSUE TITLE
missing free in `get_user_array_dim`

### ISSUE THREAD

**Issue by richfitz** [richfitz/odin#66]
In generated code i see a calloc but no free

**Comment by richfitz** [comment]
The way this is used, it is not actually required to do a copy at all.  I'll need to rewrite `get_user_array_copy` though as a version that returns a reference (and that will probably need splitting into two types)

**Comment by am70** [comment]
Yes.

**Comment by richfitz** [comment]
I have this nailed down here and will get it done tomorrow once I have time to set some test cases up so I can spot future regressions.  Thanks for helping nail this down

**Comment by am70** [comment]
No problem :)
