### ISSUE TITLE
Possible indexing bug

### ISSUE THREAD

**Issue by ada-w-yan** [richfitz/odin#78]
In the attached minimal example, after running minimal_example.R,
`mod$deriv(0, mod$init)`
should return
`4 0 0 0 0`
but instead returns
`2 0 0 0 0`

If we look inside model_minimal.R, `deriv(I)` should be assigned the value `S[2,2]`, but instead it has been assigned the value `S[2,1]`.

Looking at the C code generated by odin shows that the error occurs because of missing brackets when converting from 1-indexing to 0-indexing.
The incorrect line is line 112; line 113 contains my comment with what I think is the correct line.
Of course, I could have made a mistake somewhere to cause the issue, in which case I apologise.

[minimal_example.zip](https://github.com/richfitz/odin/files/1153057/minimal_example.zip)

**Comment by richfitz** [comment]
Can confirm - definitely a bug

**Comment by richfitz** [comment]
Thanks so much for this, and for the excellent report.  Can you try now with your full model and make sure that things work?

**Comment by ada-w-yan** [comment]
All working now, thank you!
